-- Suppression des tables
DROP TABLE IF EXISTS Fournit;
DROP TABLE IF EXISTS Reserve;
DROP TABLE IF EXISTS Participe;
DROP TABLE IF EXISTS Tente;
DROP TABLE IF EXISTS Activite;
DROP TABLE IF EXISTS Restauration;
DROP TABLE IF EXISTS Traiteur;
DROP TABLE IF EXISTS Salarie;
DROP TABLE IF EXISTS Client;
DROP TABLE IF EXISTS Ville;
